# Generated by Django 4.2.6 on 2024-02-12 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(default=False, verbose_name="author status"),
        ),
        migrations.AlterField(
            model_name="user",
            name="special_user",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 12, 18, 41, 32, 163282, tzinfo=datetime.timezone.utc
                ),
                verbose_name="special user",
            ),
        ),
    ]
