# Generated by Django 4.2.6 on 2024-02-12 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_is_author_alter_user_special_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="special_user",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 18, 42, 21, 113331, tzinfo=datetime.timezone.utc
                ),
                verbose_name="special user",
            ),
        ),
    ]
