# Generated by Django 4.2.6 on 2024-02-12 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_user_special_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="special_user",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 12, 22, 48, 58, 932664, tzinfo=datetime.timezone.utc
                ),
                verbose_name="special user",
            ),
        ),
    ]
