# Generated by Django 4.2.3 on 2023-08-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Enter your number'),
        ),
    ]
