# Generated by Django 4.2.3 on 2023-10-17 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorite',
            field=models.ManyToManyField(blank=None, default=None, null=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
