# Generated by Django 4.2.3 on 2023-11-16 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_article_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favorite',
            field=models.ManyToManyField(blank=None, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enter your number'),
        ),
    ]
